name: Test Ring 1

on:
  pull_request:
    types: [labeled]

jobs:
  handle_test_ring_1_label:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Check if label is "test-ring-1"
      if: ${{ github.event.label.name == 'test-ring-1' }}
      run: |
        echo "Label is test-ring-1, commenting and removing label..."
        # Comment "hello world"
        echo "hello world"
        # Remove label
        gh pr edit --remove-label ${GITHUB_EVENT_PULL_REQUEST} test-ring-1