name: test comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo ${{ github.head_ref }}
      - shell: bash
        run: echo ${{ github.ref }}
      - shell: bash
        run: echo ${{ github.sha }}
      - shell: bash
        run: echo ${{ github.workflow_sha }}
      - shell: bash
        run: echo '${{ toJSON(github) }}'

