name: Test Ring 1

on:
  pull_request:
    types: [labeled]

jobs:
  handle_test_ring_1_label:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v4
    - name: Check if label is "test-ring-1"
      if: ${{ github.event.label.name == 'test-ring-1' }}
      env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Label is test-ring-1, commenting and removing label..."
        # Comment "hello world"
        echo "hello world"
        echo "${{ github.event.pull_request.number }}"
        # Remove label
        gh pr edit ${{ github.event.pull_request.number }} --remove-label test-ring-1
