name: 'on-check'
on: # rebuild any PRs and main branch changes
  check_run:
    types: [completed]
  check_suite:
    types: [completed]
  status:

jobs:
  print: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run:
          env